// Auto-generated from Excel order form images
export const PRODUCT_IMAGE_MAP: Record<string, string> = {
  "100PACK_ASSORTED_WATERPROOF_PLASTERS": "/product-images/fa_100PACK_ASSORTED_WATERPROOF_PLASTERS.png",
  "10PACK_LARGE_FOIL_BLANKETS": "/product-images/fa_10PACK_LARGE_FOIL_BLANKETS.png",
  "A4_ACCIDENT_REPORT_BOOK": "/product-images/fa_A4_ACCIDENT_REPORT_BOOK.png",
  "AIRLAID_TOWELS_WHITE_CASE": "/product-images/cs_AIRLAID_TOWELS_WHITE_CASE.jpg",
  "APRONS_FLTPACK_100PK": "/product-images/fa_APRONS_FLTPACK_100PK.jpg",
  "BARRIER_TAPE_NON_ADHESIVE_RED/WHITE": "/product-images/cs_BARRIER_TAPE_NON_ADHESIVE_RED_WHITE.png",
  "BIO_HAZARD_KITS": "/product-images/fa_BIO_HAZARD_KITS.png",
  "BODYFORM_HYGIENE_PADS_12PACK": "/product-images/fa_BODYFORM_HYGIENE_PADS_12PACK.png",
  "BRUSH_STIFF_28CM + HANDLE_BLUE": "/product-images/cs_BRUSH_STIFF_28CM___HANDLE_BLUE.png",
  "BRUSH_STIFF_28CM + HANDLE_RED": "/product-images/cs_BRUSH_STIFF_28CM___HANDLE_RED.jpg",
  "BRUSH_STIFF_45CM + ALLOY_HANDLE_BLUE": "/product-images/cs_BRUSH_STIFF_45CM___ALLOY_HANDLE_BLUE.png",
  "BRUSH_STIFF_45CM + ALLOY_HANDLE_RED": "/product-images/cs_BRUSH_STIFF_45CM___ALLOY_HANDLE_RED.jpg",
  "BUCKET_OVAL_MOP_14L_RED": "/product-images/cs_BUCKET_OVAL_MOP_14L_RED.png",
  "BUCKET_PLASTIC_10L_RED": "/product-images/cs_BUCKET_PLASTIC_10L_RED.png",
  "CENTRE_FEED_ST_BLUE_6PK": "/product-images/fa_CENTRE_FEED_ST_BLUE_6PK.jpg",
  "CFOLD_2295_2PLY_WHITE": "/product-images/cs_CFOLD_2295_2PLY_WHITE.jpg",
  "CLOTH_FLOOR_WHITE_10PK": "/product-images/cs_CLOTH_FLOOR_WHITE_10PK.png",
  "CLOTH_MFIBRE_BLUE_10PK": "/product-images/cs_CLOTH_MFIBRE_BLUE_10PK.jpg",
  "CLOTH_OCEAN_RED_50PK": "/product-images/cs_CLOTH_OCEAN_RED_50PK.jpg",
  "CLOVER_DETAK_750ML": "/product-images/cs_CLOVER_DETAK_750ML.png",
  "CLOVER_HAND_SOAP_1L": "/product-images/cs_CLOVER_HAND_SOAP_1L.png",
  "CLOVER_ULTRAFRESH_1L": "/product-images/cs_CLOVER_ULTRAFRESH_1L.gif",
  "COCLENS_SKINSOL_500ML": "/product-images/fa_COCLENS_SKINSOL_500ML.png",
  "COUCH_ROLL_50CMX50M": "/product-images/fa_COUCH_ROLL_50CMX50M.png",
  "DISP_PILLOW_50PACK": "/product-images/fa_DISP_PILLOW_50PACK.png",
  "DUSTPAN_BRUSH_SET_RED": "/product-images/cs_DUSTPAN_BRUSH_SET_RED.jpg",
  "DUSTPAN_BRUSH_SET_YELLOW": "/product-images/cs_DUSTPAN_BRUSH_SET_YELLOW.jpg",
  "EAB_INJURY_BANDAGE_5CMX4.5M": "/product-images/fa_EAB_INJURY_BANDAGE_5CMX4_5M.png",
  "ECB_BANDAGE_5CMX4M": "/product-images/fa_ECB_BANDAGE_5CMX4M.jpg",
  "EYEWASH_INCCAP_500ML": "/product-images/fa_EYEWASH_INCCAP_500ML.jpg",
  "EYEWEAR_SAFETY_GOGGLES_CLEAR": "/product-images/cs_EYEWEAR_SAFETY_GOGGLES_CLEAR.jpg",
  "FACEMASK_BLUE_50PACK": "/product-images/fa_FACEMASK_BLUE_50PACK.png",
  "FIRSTAID_KIT_LARGE_188P": "/product-images/fa_FIRSTAID_KIT_LARGE_188P.png",
  "FIRSTAID_KIT_MEDIUM_126P": "/product-images/fa_FIRSTAID_KIT_MEDIUM_126P.png",
  "GLOVES_NITRILE-POLY_FOAM_S_10PACK": "/product-images/cs_GLOVES_NITRILE-POLY_FOAM_S_10PACK.png",
  "GLOVES_NITRILE_BLUE_SML": "/product-images/fa_GLOVES_NITRILE_BLUE_SML.png",
  "GLOVES_VINYL_CLEAR_SML": "/product-images/fa_GLOVES_VINYL_CLEAR_SML.jpg",
  "HI_VIS_ORANGE_LS_S": "/product-images/cs_HI_VIS_ORANGE_LS_S.png",
  "HI_VIS_ORANGE_S": "/product-images/cs_HI_VIS_ORANGE_S.jpg",
  "HI_VIS_ORG/BLUE_EXEC_S": "/product-images/cs_HI_VIS_ORG_BLUE_EXEC_S.png",
  "HI_VIS_ORG/BLUE_EXEC_XXL": "/product-images/cs_HI_VIS_ORG_BLUE_EXEC_XXL.png",
  "HI_VIS_PINK_S": "/product-images/cs_HI_VIS_PINK_S.png",
  "HI_VIS_PINK_XXL": "/product-images/cs_HI_VIS_PINK_XXL.png",
  "HI_VIS_RED_S": "/product-images/cs_HI_VIS_RED_S.png",
  "HI_VIS_YELL/R.NAVY_EXEC_S": "/product-images/cs_HI_VIS_YELL_R_NAVY_EXEC_S.png",
  "HI_VIS_YELLOW_BS_S": "/product-images/cs_HI_VIS_YELLOW_BS_S.jpg",
  "HI_VIS_YELLOW_EXEC_S": "/product-images/cs_HI_VIS_YELLOW_EXEC_S.jpg",
  "HI_VIS_YELLOW_LS_S": "/product-images/cs_HI_VIS_YELLOW_LS_S.png",
  "HI_VIS_YELLOW_S": "/product-images/cs_HI_VIS_YELLOW_S.png",
  "HI_VIS_YELLOW_S_FA": "/product-images/fa_HI_VIS_YELLOW_S_FA.png",
  "IMPACT_LIQUIDS_MULTI_PURPOSE_5L": "/product-images/cs_IMPACT_LIQUIDS_MULTI_PURPOSE_5L.gif",
  "JUG_FUNNEL_6\"": "/product-images/cs_JUG_FUNNEL_6_.jpg",
  "KOOLPAK_RESUSE_13CMx14CM": "/product-images/fa_KOOLPAK_RESUSE_13CMx14CM.png",
  "LOBBY_BRUSH_LONGHNDL_COMPLETE_SET_BLACK": "/product-images/cs_LOBBY_BRUSH_LONGHNDL_COMPLETE_SET_BLACK.jpg",
  "MAINTENCE REFILL PADS_X20": "/product-images/fa_MAINTENCE_REFILL_PADS_X20.jpg",
  "MASK_DISP_DUSTCLEAR_50PK": "/product-images/cs_MASK_DISP_DUSTCLEAR_50PK.jpg",
  "MEDIPAL_AW_150P": "/product-images/fa_MEDIPAL_AW_150P.png",
  "MOP_DISP_RED_10PK": "/product-images/cs_MOP_DISP_RED_10PK.jpg",
  "MOP_STAND_PY(12)_7OZ_RED": "/product-images/cs_MOP_STAND_PY_12__7OZ_RED.jpg",
  "PUMP_30CC_FOR_5L": "/product-images/cs_PUMP_30CC_FOR_5L.jpg",
  "REFUSE_SACK_BLACK_100PK": "/product-images/cs_REFUSE_SACK_BLACK_100PK.png",
  "ROLLER_DIVIDE_100CMX200CM": "/product-images/fa_ROLLER_DIVIDE_100CMX200CM.jpg",
  "SCISSORS_INSTRAPAC_SS_13CM": "/product-images/fa_SCISSORS_INSTRAPAC_SS_13CM.png",
  "SCISSORS_SUPERSNIP_SS": "/product-images/fa_SCISSORS_SUPERSNIP_SS.png",
  "SCRAPER": "/product-images/cs_SCRAPER.png",
  "SHARPS_CONTAINER_13L": "/product-images/fa_SHARPS_CONTAINER_13L.png",
  "SPILL_KITS_MAINTENANCE_10L": "/product-images/fa_SPILL_KITS_MAINTENANCE_10L.jpg",
  "SPILL_KITS_MAINTENANCE_15L": "/product-images/fa_SPILL_KITS_MAINTENANCE_15L.jpg",
  "SPILL_KITS_MAINTENANCE_20L": "/product-images/fa_SPILL_KITS_MAINTENANCE_20L.jpg",
  "SPILL_KITS_MAINTENANCE_50L": "/product-images/fa_SPILL_KITS_MAINTENANCE_50L.jpg",
  "SQUEEGEE_METAL_55CM": "/product-images/cs_SQUEEGEE_METAL_55CM.png",
  "STATION_EYEWASH_TRIPLE": "/product-images/fa_STATION_EYEWASH_TRIPLE.jpg",
  "TISSUE_FACIAL_100SHEETS": "/product-images/fa_TISSUE_FACIAL_100SHEETS.png",
  "TOILET_BRUSH_HOLDER_WHITE": "/product-images/cs_TOILET_BRUSH_HOLDER_WHITE.png",
  "TRAVEL_BED": "/product-images/fa_TRAVEL_BED.jpg",
  "TRG_COMPLETE_RED": "/product-images/cs_TRG_COMPLETE_RED.jpg",
  "TR_JUMBO_MINI_12PK": "/product-images/cs_TR_JUMBO_MINI_12PK.jpg",
  "VOMIT_BAGS_50PACK": "/product-images/fa_VOMIT_BAGS_50PACK.png",
  "WET_FLOOR_AFRAME": "/product-images/fa_WET_FLOOR_AFRAME.png",
  "WHEEL_CHAIR_MKII": "/product-images/fa_WHEEL_CHAIR_MKII.png",
  "WRAP_CELLOPHANE_CLEAR": "/product-images/cs_WRAP_CELLOPHANE_CLEAR.png",
  "KTY_BUFFALO_BUCKET_WRINGER_25L_RED": "/product-images/KTY_BUFFALO_BUCKET_WRINGER_25L_RED.jpg",
};
