// Auto-generated from Excel order form — product descriptions and size labels
export const PRODUCT_DESCRIPTION_MAP: Record<string, string> = {
  "AIRLAID_TOWELS_WHITE_CASE": "Airlaid - White - Luxury Paper Hand Towels",
  "APRONS_FLTPACK_100PK": "Disposable White Polythene Aprons",
  "ASSURED_BW_500M_3PACK": "Bubble Wrap",
  "BARRIER_TAPE_NON_ADHESIVE_BLACK/YELLOW": "Non-Adhesive Hazard Warning Tape - 500m per Roll",
  "BARRIER_TAPE_NON_ADHESIVE_BLACK/YELLOW_10PK": "Non-Adhesive Hazard Warning Tape - 500m per Roll",
  "BARRIER_TAPE_NON_ADHESIVE_RED/WHITE": "Non-Adhesive Hazard Warning Tape - 500m per Roll",
  "BARRIER_TAPE_NON_ADHESIVE_RED/WHITE_10PK": "Non-Adhesive Hazard Warning Tape - 500m per Roll",
  "BIO_HAZARD_KITS": "Bio Hazard Spill Kit",
  "BRUSH_SOFT_28CM + HANDLE_BLUE": "Robert Scott Blue Stiff or Soft Brush with Coloured Metal handle",
  "BRUSH_SOFT_28CM + HANDLE_RED": "Robert Scott Red Stiff or Soft Brush with Coloured Metal handle",
  "BRUSH_SOFT_30CM + ALLOY_HANDLE_BLUE": "Robert Scott Professional Hygiene Blue Stiff or Soft Brush with strong Alloy Handle",
  "BRUSH_SOFT_30CM + ALLOY_HANDLE_RED": "Robert Scott Professional Hygiene Red Stiff or Soft Brush with strong Alloy Handle",
  "BRUSH_SOFT_45CM + ALLOY_HANDLE_BLUE": "Robert Scott Professional Hygiene Blue Stiff or Soft Brush with strong Alloy Handle",
  "BRUSH_SOFT_45CM + ALLOY_HANDLE_RED": "Robert Scott Professional Hygiene Red Stiff or Soft Brush with strong Alloy Handle",
  "BRUSH_STIFF_28CM + HANDLE_BLUE": "Robert Scott Blue Stiff or Soft Brush with Coloured Metal handle",
  "BRUSH_STIFF_28CM + HANDLE_RED": "Robert Scott Red Stiff or Soft Brush with Coloured Metal handle",
  "BRUSH_STIFF_30CM + ALLOY_HANDLE_BLUE": "Robert Scott Professional Hygiene Blue Stiff or Soft Brush with strong Alloy Handle",
  "BRUSH_STIFF_30CM + ALLOY_HANDLE_RED": "Robert Scott Professional Hygiene Red Stiff or Soft Brush with strong Alloy Handle",
  "BRUSH_STIFF_45CM + ALLOY_HANDLE_BLUE": "Robert Scott Professional Hygiene Blue Stiff or Soft Brush with strong Alloy Handle",
  "BRUSH_STIFF_45CM + ALLOY_HANDLE_RED": "Robert Scott Professional Hygiene Red Stiff or Soft Brush with strong Alloy Handle",
  "BUCKET_OVAL_MOP_14L_BLUE": "Robert Scott Exel Mop Bucket And Wringer 14 Litre",
  "BUCKET_OVAL_MOP_14L_GREEN": "Robert Scott Exel Mop Bucket And Wringer 14 Litre",
  "BUCKET_OVAL_MOP_14L_RED": "Robert Scott Exel Mop Bucket And Wringer 14 Litre",
  "BUCKET_OVAL_MOP_14L_YELLOW": "Robert Scott Exel Mop Bucket And Wringer 14 Litre",
  "BUCKET_PLASTIC_10L_BLUE": "Robert Scoot Plastic Bucket With Handle 10 Litre",
  "BUCKET_PLASTIC_10L_GREEN": "Robert Scoot Plastic Bucket With Handle 10 Litre",
  "BUCKET_PLASTIC_10L_RED": "Robert Scoot Plastic Bucket With Handle 10 Litre",
  "CENTRE_FEED_BLUE_DL_6PK": "6 Pack of Centre Feed Paper Rolls",
  "CENTRE_FEED_ST_BLUE_6PK": "6 Pack of Centre Feed Paper Rolls - Economy",
  "CENTRE_FEED_ST_WHITE_6PK": "6 Pack of Centre Feed Paper Rolls - Economy",
  "CENTRE_FEED_WHITE_DL_6PK": "6 Pack of Centre Feed Paper Rolls",
  "CFOLD_2295_2PLY_WHITE": "C-Fold Hand Towels, Case of 2400 (Price on Application - Qty Dependant)",
  "CFOLD_2400_1PLY_BLUE": "C-Fold Hand Towels, Case of 2400 (Price on Application - Qty Dependant)",
  "CFOLD_2400_1PLY_GREEN": "C-Fold Hand Towels, Case of 2400 (Price on Application - Qty Dependant)",
  "CLOTH_FLOOR_WHITE_10PK": "Robert Scott Large Bleached White Dish Cloth - Pack of 10",
  "CLOTH_MFIBRE_BLUE_10PK": "Robert Scott Professional Microfibre Exel Supercloth Pack of 10",
  "CLOTH_MFIBRE_GREEN_10PK": "Robert Scott Professional Microfibre Exel Supercloth Pack of 10",
  "CLOTH_MFIBRE_PINK_10PK": "Robert Scott Professional Microfibre Exel Supercloth Pack of 10",
  "CLOTH_MFIBRE_WHITE_10PK": "Robert Scott Professional Microfibre Exel Supercloth Pack of 10",
  "CLOTH_MFIBRE_YELLOW_10PK": "Robert Scott Professional Microfibre Exel Supercloth Pack of 10",
  "CLOTH_OCEAN_BLUE_50PK": "Robert Scott Anti-Bacterial Cleaning Ocean Cloths - Pack of 50",
  "CLOTH_OCEAN_GREEN_50PK": "Robert Scott Anti-Bacterial Cleaning Ocean Cloths - Pack of 50",
  "CLOTH_OCEAN_RED_50PK": "Robert Scott Anti-Bacterial Cleaning Ocean Cloths - Pack of 50",
  "CLOVER_AHS_300ML": "Anti Bacterial Hand Sanitizer/Gel 70% Alcohol)",
  "CLOVER_AHS_5L": "Anti Bacterial Hand Sanitizer/Gel 70% Alcohol)",
  "CLOVER_DETAK_750ML": "Chewing Gum Remover",
  "CLOVER_HAND_SOAP_1L": "Anti Bacterial Hand Soap",
  "CLOVER_HAND_SOAP_5L": "Anti Bacterial Hand Soap",
  "CLOVER_ULTRAFRESH_1L": "Impact Professional Washroom Cleaner (1:50 Dilution Rate)",
  "CLOVER_ULTRAFRESH_5L": "Impact Professional Washroom Cleaner (1:50 Dilution Rate)",
  "COUCH_ROLL_50CMX50M": "6 Pack of Centre Feed Paper Rolls",
  "DISP_PILLOW_50PACK": "6 Pack of Centre Feed Paper Rolls",
  "DUSTPAN_BRUSH_SET_BLUE": "Robert Scott - Dust Pan & Brush Set",
  "DUSTPAN_BRUSH_SET_GREEN": "Robert Scott - Dust Pan & Brush Set",
  "DUSTPAN_BRUSH_SET_RED": "Robert Scott - Dust Pan & Brush Set",
  "DUSTPAN_BRUSH_SET_YELLOW": "Robert Scott - Dust Pan & Brush Set",
  "EYEWEAR_SAFETY_GLASSES_CLEAR": "Personal Protection - Masks, Safety Goggles & Glasses",
  "EYEWEAR_SAFETY_GOGGLES_CLEAR": "Personal Protection - Masks, Safety Goggles & Glasses",
  "FACEMASK_BLUE_50PACK": "Disposable White Polythene Aprons",
  "GLOVES_NITRILE-POLY_FOAM_L_10PACK": "Work Gloves - Compliant with EN388: 2016 Level 4 - Abrasion Level X - Cut Resistance Level 2 - Tear Resistance Level 1 - Puncture",
  "GLOVES_NITRILE-POLY_FOAM_M_10PACK": "Work Gloves - Compliant with EN388: 2016 Level 4 - Abrasion Level X - Cut Resistance Level 2 - Tear Resistance Level 1 - Puncture",
  "GLOVES_NITRILE-POLY_FOAM_S_10PACK": "Work Gloves - Compliant with EN388: 2016 Level 4 - Abrasion Level X - Cut Resistance Level 2 - Tear Resistance Level 1 - Puncture",
  "GLOVES_NITRILE-POLY_FOAM_XL_10PACK": "Work Gloves - Compliant with EN388: 2016 Level 4 - Abrasion Level X - Cut Resistance Level 2 - Tear Resistance Level 1 - Puncture",
  "GLOVES_NITRILE_BLUE_L": "Nitrile Gloves - Latex Free - 50 Pairs per box",
  "GLOVES_NITRILE_BLUE_MED": "Nitrile Gloves - Latex Free - 50 Pairs per box",
  "GLOVES_NITRILE_BLUE_SML": "Nitrile Gloves - Latex Free - 50 Pairs per box",
  "GLOVES_NITRILE_BLUE_XL": "Nitrile Gloves - Latex Free - 50 Pairs per box",
  "GLOVES_VINYL_CLEAR_L": "Clear Vinyl Gloves - Powder Free - 50 Pairs per box",
  "GLOVES_VINYL_CLEAR_MED": "Clear Vinyl Gloves - Powder Free - 50 Pairs per box",
  "GLOVES_VINYL_CLEAR_SML": "Clear Vinyl Gloves - Powder Free - 50 Pairs per box",
  "GLOVES_VINYL_CLEAR_XL": "Clear Vinyl Gloves - Powder Free - 50 Pairs per box",
  "HI_VIS_BLUE_L": "Blue Hi Vis Vest - EN ISO 20471 Compliant",
  "HI_VIS_BLUE_M": "Blue Hi Vis Vest - EN ISO 20471 Compliant",
  "HI_VIS_BLUE_S": "Blue Hi Vis Vest - EN ISO 20471 Compliant",
  "HI_VIS_BLUE_XL": "Blue Hi Vis Vest - EN ISO 20471 Compliant",
  "HI_VIS_BLUE_XXL": "Blue Hi Vis Vest - EN ISO 20471 Compliant",
  "HI_VIS_ORANGE_L": "Orange High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_ORANGE_LS_L": "Orange Long Sleeve High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_ORANGE_LS_M": "Orange Long Sleeve High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_ORANGE_LS_S": "Orange Long Sleeve High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_ORANGE_LS_XL": "Orange Long Sleeve High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_ORANGE_LS_XXL": "Orange Long Sleeve High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_ORANGE_M": "Orange High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_ORANGE_S": "Orange High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_ORANGE_XL": "Orange High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_ORANGE_XXL": "Orange High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_ORG/BLUE_EXEC_L": "Zipped Orange & Blue Executive High Visibility Vest with Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_ORG/BLUE_EXEC_M": "Zipped Orange & Blue Executive High Visibility Vest with Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_ORG/BLUE_EXEC_S": "Zipped Orange & Blue Executive High Visibility Vest with Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_ORG/BLUE_EXEC_XL": "Zipped Orange & Blue Executive High Visibility Vest with Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_ORG/BLUE_EXEC_XXL": "Zipped Orange & Blue Executive High Visibility Vest with Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_PINK_L": "Pink Hi Vis Vest - EN ISO 20471 Compliant",
  "HI_VIS_PINK_M": "Pink Hi Vis Vest - EN ISO 20471 Compliant",
  "HI_VIS_PINK_S": "Pink Hi Vis Vest - EN ISO 20471 Compliant",
  "HI_VIS_PINK_XL": "Pink Hi Vis Vest - EN ISO 20471 Compliant",
  "HI_VIS_PINK_XXL": "Pink Hi Vis Vest - EN ISO 20471 Compliant",
  "HI_VIS_RED/GREY_EXEC_L": "Zipped Red & Grey Executive High Visibility Vest with Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_RED/GREY_EXEC_M": "Zipped Red & Grey Executive High Visibility Vest with Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_RED/GREY_EXEC_S": "Zipped Red & Grey Executive High Visibility Vest with Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_RED/GREY_EXEC_XL": "Zipped Red & Grey Executive High Visibility Vest with Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_RED/GREY_EXEC_XXL": "Zipped Red & Grey Executive High Visibility Vest with Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_RED_L": "Red High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_RED_M": "Red High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_RED_S": "Red High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_RED_XL": "Red High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_RED_XXL": "Red High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELL/R.NAVY_EXEC_L": "Zipped Yellow & Blue Executive High Visibility Vest with Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELL/R.NAVY_EXEC_M": "Zipped Yellow & Blue Executive High Visibility Vest with Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELL/R.NAVY_EXEC_S": "Zipped Yellow & Blue Executive High Visibility Vest with Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELL/R.NAVY_EXEC_XL": "Zipped Yellow & Blue Executive High Visibility Vest with Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELL/R.NAVY_EXEC_XXL": "Zipped Yellow & Blue Executive High Visibility Vest with Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELLOW_BS_L": "Yellow Hi Vis Vest - Economy/Basic",
  "HI_VIS_YELLOW_BS_M": "Yellow Hi Vis Vest - Economy/Basic",
  "HI_VIS_YELLOW_BS_S": "Yellow Hi Vis Vest - Economy/Basic",
  "HI_VIS_YELLOW_BS_XL": "Yellow Hi Vis Vest - Economy/Basic",
  "HI_VIS_YELLOW_BS_XXL": "Yellow Hi Vis Vest - Economy/Basic",
  "HI_VIS_YELLOW_EXEC_L": "Zipped Orange & Yellow Executive High Visibility Vest with Telephone and Badge Holder & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELLOW_EXEC_M": "Zipped Orange & Yellow Executive High Visibility Vest with Telephone and Badge Holder & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELLOW_EXEC_S": "Zipped Orange & Yellow Executive High Visibility Vest with Telephone and Badge Holder & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELLOW_EXEC_XL": "Zipped Orange & Yellow Executive High Visibility Vest with Telephone and Badge Holder & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELLOW_EXEC_XXL": "Zipped Orange & Yellow Executive High Visibility Vest with Telephone and Badge Holder & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELLOW_L": "Yellow High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELLOW_LS_L": "Yellow Long Sleeve High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELLOW_LS_M": "Yellow Long Sleeve High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELLOW_LS_S": "Yellow Long Sleeve High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELLOW_LS_XL": "Yellow Long Sleeve High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELLOW_LS_XXL": "Yellow Long Sleeve High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELLOW_L_FA": "FIRST AID Yellow High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELLOW_M": "Yellow High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELLOW_M_FA": "FIRST AID Yellow High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELLOW_S": "Yellow High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELLOW_S_FA": "FIRST AID Yellow High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELLOW_XL": "Yellow High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELLOW_XL_FA": "FIRST AID Yellow High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELLOW_XXL": "Yellow High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HI_VIS_YELLOW_XXL_FA": "FIRST AID Yellow High Visibility Vest with Velcro Front Fastening & Reflective Strips - EN ISO 20471 Compliant",
  "HNDL_SQUEEGEE_PLASTIC": "Robert Scott Floor Squeegee",
  "HNDL_WOODEN": "Robert Scott Standard PY(12) 7oz Mop Heads",
  "HNDL_WOODEN_1": "Robert Scott Disposable Mop Heads Pack of 10",
  "HNDL_WOODEN_2": "Robert Scott Floor Squeegee",
  "IMPACT_LIQUIDS_MULTI_PURPOSE_5L": "Zesty Lemon Floor Cleaner & Degreaser",
  "JUG_FUNNEL_6\"": "Plastic Pouring Funnel",
  "JUG_MEASURING_1LITRE": "Plastic Pouring Jug",
  "LITTER_PICKER_34INCH": "Litter Pickers",
  "LOBBY_BRUSH_LONGHNDL_COMPLETE_SET_BLACK": "Robert Scott Long Handled Lobby Brush - Complete Set",
  "LOBBY_BRUSH_LONGHNDL_COMPLETE_SET_BLUE": "Robert Scott Long Handled Lobby Brush - Complete Set",
  "LOBBY_BRUSH_LONGHNDL_COMPLETE_SET_GREEN": "Robert Scott Long Handled Lobby Brush - Complete Set",
  "LOBBY_BRUSH_LONGHNDL_COMPLETE_SET_RED": "Robert Scott Long Handled Lobby Brush - Complete Set",
  "LOBBY_BRUSH_LONGHNDL_COMPLETE_SET_YELLOW": "Robert Scott Long Handled Lobby Brush - Complete Set",
  "MAINTENCE REFILL PADS_X20": "Bio Hazard Spill Kit",
  "MASK_DISP_DUSTCLEAR_50PK": "Personal Protection - Masks, Safety Goggles & Glasses",
  "MOP_DISP_BLUE_10PK": "Robert Scott Disposable Mop Heads Pack of 10",
  "MOP_DISP_GREEN_10PK": "Robert Scott Disposable Mop Heads Pack of 10",
  "MOP_DISP_RED_10PK": "Robert Scott Disposable Mop Heads Pack of 10",
  "MOP_STAND_PY(12)_7OZ_BLUE": "Robert Scott Standard PY(12) 7oz Mop Heads",
  "MOP_STAND_PY(12)_7OZ_GREEN": "Robert Scott Standard PY(12) 7oz Mop Heads",
  "MOP_STAND_PY(12)_7OZ_RED": "Robert Scott Standard PY(12) 7oz Mop Heads",
  "PUMP_30CC_FOR_5L": "Bio Hazard Spill Kit",
  "REFUSE_BIN_LINERS_CLEAR_1000PK": "Refuse / Bin Liners Bags",
  "REFUSE_SACK_BLACK_100PK": "Refuse / Bin Liners Bags",
  "REFUSE_SACK_CLEAR__100PK": "Refuse / Bin Liners Bags",
  "ROLLER_DIVIDE_100CMX200CM": "6 Pack of Centre Feed Paper Rolls",
  "SCRAPER": "Scraper",
  "SHARPS_CONTAINER_13L": "Medical Sharps Bins (Complaint with UN 3291, BS EN ISO 23907:2012 and NF-X-30-500)",
  "SHARPS_CONTAINER_1L": "Medical Sharps Bins (Complaint with UN 3291, BS EN ISO 23907:2012 and NF-X-30-500)",
  "SHARPS_CONTAINER_2L": "Medical Sharps Bins (Complaint with UN 3291, BS EN ISO 23907:2012 and NF-X-30-500)",
  "SHARPS_CONTAINER_7L": "Medical Sharps Bins (Complaint with UN 3291, BS EN ISO 23907:2012 and NF-X-30-500)",
  "SPILL_KITS_MAINTENANCE_10L": "Bio Hazard Spill Kit",
  "SPILL_KITS_MAINTENANCE_15L": "Bio Hazard Spill Kit",
  "SPILL_KITS_MAINTENANCE_20L": "Bio Hazard Spill Kit",
  "SPILL_KITS_MAINTENANCE_50L": "Bio Hazard Spill Kit",
  "SQUEEGEE_METAL_55CM": "Robert Scott Floor Squeegee",
  "SQUEEGEE_PLASTIC_55CM": "Robert Scott Floor Squeegee",
  "TISSUE_FACIAL_100SHEETS": "Bio Hazard Spill Kit",
  "TOILET_BRUSH_HOLDER_WHITE": "Robert Scott - Toilet Brush & Holder",
  "TRAVEL_BED": "6 Pack of Centre Feed Paper Rolls",
  "TRG_COMPLETE_BLUE": "Taylor Davis 750ml Complete Sprayer Bottles & Replacement Trigger Heads",
  "TRG_COMPLETE_GREEN": "Taylor Davis 750ml Complete Sprayer Bottles & Replacement Trigger Heads",
  "TRG_COMPLETE_RED": "Taylor Davis 750ml Complete Sprayer Bottles & Replacement Trigger Heads",
  "TRG_HEAD_ONLY_BLUE": "Taylor Davis 750ml Complete Sprayer Bottles & Replacement Trigger Heads",
  "TRG_HEAD_ONLY_GREEN": "Taylor Davis 750ml Complete Sprayer Bottles & Replacement Trigger Heads",
  "TRG_HEAD_ONLY_RED": "Taylor Davis 750ml Complete Sprayer Bottles & Replacement Trigger Heads",
  "TR_JUMBO_MINI_12PK": "Toilet Rolls (Price on Application - Qty Dependant)",
  "TR_STANDARD_WHITE_36PK": "Toilet Rolls (Price on Application - Qty Dependant)",
  "VOMIT_BAGS_50PACK": "Medical Sharps Bins (Complaint with UN 3291, BS EN ISO 23907:2012 and NF-X-30-500)",
  "WET_FLOOR_AFRAME": "Wet Floor Sign",
  "WHEEL_CHAIR_MKII": "6 Pack of Centre Feed Paper Rolls",
  "WRAP_CELLOPHANE_CLEAR": "Cellophane Wrap",
};

export const PRODUCT_SIZE_MAP: Record<string, string> = {
  "AIRLAID_TOWELS_WHITE_CASE": "10 Packs x 50 Executive Airlaid Towels (40cm x 40cm)",
  "APRONS_FLTPACK_100PK": "Flat Pack of 100 Aprons - 10 Microns, 686m (w) x 1000m (h)",
  "ASSURED_BW_500M_3PACK": "3 Pack of 500mm x 100m",
  "BARRIER_TAPE_NON_ADHESIVE_BLACK/YELLOW": "Black & Yellow Hazard Warning Roll (Non-Adhesive)",
  "BARRIER_TAPE_NON_ADHESIVE_BLACK/YELLOW_10PK": "Black & Yellow Box of 10 Rolls (Non-Adhesive)",
  "BARRIER_TAPE_NON_ADHESIVE_RED/WHITE": "Red & White Hazard Warning Roll (Non-Adhesive)",
  "BARRIER_TAPE_NON_ADHESIVE_RED/WHITE_10PK": "Red & White Box of 10 Rolls (Non-Adhesive)",
  "BIO_HAZARD_KITS": "1 Disinfectant Spray (8ml) / 1 Absorbent Granules (10g) - 1 Disposable Gloves (pair) / 1 Polythene Apron - 1 Scoop/Scraper / 2 Dry Wipes - 1 Biohazard Bag / 1 Disinfectant Wipe - 1 Pack Tissues (10)",
  "BRUSH_SOFT_28CM + HANDLE_BLUE": "28cm Soft Brush & Handle",
  "BRUSH_SOFT_28CM + HANDLE_RED": "28cm Soft Brush & Handle",
  "BRUSH_SOFT_30CM + ALLOY_HANDLE_BLUE": "30cm Soft Brush & Handle",
  "BRUSH_SOFT_30CM + ALLOY_HANDLE_RED": "30cm Soft Brush & Handle",
  "BRUSH_SOFT_45CM + ALLOY_HANDLE_BLUE": "45cm Soft Brush & Handle",
  "BRUSH_SOFT_45CM + ALLOY_HANDLE_RED": "45cm Soft Brush & Handle",
  "BRUSH_STIFF_28CM + HANDLE_BLUE": "28cm Stiff Brush & Handle",
  "BRUSH_STIFF_28CM + HANDLE_RED": "28cm Stiff Brush & Handle",
  "BRUSH_STIFF_30CM + ALLOY_HANDLE_BLUE": "30cm Stiff Brush & Handle",
  "BRUSH_STIFF_30CM + ALLOY_HANDLE_RED": "30cm Stiff Brush & Handle",
  "BRUSH_STIFF_45CM + ALLOY_HANDLE_BLUE": "45cm Stiff Brush & Handle",
  "BRUSH_STIFF_45CM + ALLOY_HANDLE_RED": "45cm Stiff Brush & Handle",
  "BUCKET_OVAL_MOP_14L_BLUE": "14L Mop Bucket Complete with Handle & Wringer - Blue",
  "BUCKET_OVAL_MOP_14L_GREEN": "14L Mop Bucket Complete with Handle & Wringer - Green",
  "BUCKET_OVAL_MOP_14L_RED": "14L Mop Bucket Complete with Handle & Wringer - Red",
  "BUCKET_OVAL_MOP_14L_YELLOW": "14L Mop Bucket Complete with Handle & Wringer - Yellow",
  "BUCKET_PLASTIC_10L_BLUE": "10L Plastic Bucket with Handle - Blue",
  "BUCKET_PLASTIC_10L_GREEN": "10L Plastic Bucket with Handle - Green",
  "BUCKET_PLASTIC_10L_RED": "10L Plastic Bucket with Handle - Red",
  "CENTRE_FEED_BLUE_DL_6PK": "Premium Touch Roll, 120m length, 2 Ply Roll - Blue",
  "CENTRE_FEED_ST_BLUE_6PK": "Soft Touch Roll, 50m length - Blue",
  "CENTRE_FEED_ST_WHITE_6PK": "Soft Touch Roll, 50m length - White",
  "CENTRE_FEED_WHITE_DL_6PK": "Premium Touch Roll, 120m length, 2 Ply Roll - White",
  "CFOLD_2295_2PLY_WHITE": "White - 2Ply",
  "CFOLD_2400_1PLY_BLUE": "Blue - 1Ply",
  "CFOLD_2400_1PLY_GREEN": "Green - 1Ply",
  "CLOTH_FLOOR_WHITE_10PK": "White Cloth with Red Trim - 1275mm x 965mm",
  "CLOTH_MFIBRE_BLUE_10PK": "Premium Micofibre Cloth - 400mm x 400mm - Blue",
  "CLOTH_MFIBRE_GREEN_10PK": "Premium Micofibre Cloth - 400mm x 400mm - Green",
  "CLOTH_MFIBRE_PINK_10PK": "Premium Micofibre Cloth - 400mm x 400mm - Pink",
  "CLOTH_MFIBRE_WHITE_10PK": "Premium Micofibre Cloth - 400mm x 400mm - White",
  "CLOTH_MFIBRE_YELLOW_10PK": "Premium Micofibre Cloth - 400mm x 400mm - Yellow",
  "CLOTH_OCEAN_BLUE_50PK": "Large Handy Wipes - 600mm x 300mm - Blue",
  "CLOTH_OCEAN_GREEN_50PK": "Large Handy Wipes - 600mm x 300mm - Green",
  "CLOTH_OCEAN_RED_50PK": "Large Handy Wipes - 600mm x 300mm - Red",
  "CLOVER_AHS_300ML": "300ml Bottle",
  "CLOVER_AHS_5L": "5L Bottle",
  "CLOVER_DETAK_750ML": "Detak Chewing Gum Remover 300ml",
  "CLOVER_HAND_SOAP_1L": "1L Pump Bottle",
  "CLOVER_HAND_SOAP_5L": "5L Bottle",
  "CLOVER_ULTRAFRESH_1L": "1L Bottle - 1:50 Dilution Rate",
  "CLOVER_ULTRAFRESH_5L": "5L Bottle - 1:50 Dilution Rate",
  "COUCH_ROLL_50CMX50M": "Couch Roll 50cm(w) x 50m(l) Suitable for covering couches and benches. May also be used for general purpose wiping. Aids high levels of hygiene. Protects your Examination Couch Saves Money on Cleaning Materials Economic in Use Fits Standard Couch Roll Holders 50 metres length",
  "DISP_PILLOW_50PACK": "Disposable Pillow Cases (Pack of 50) - Inner flaps - Independently tested for flame retardancy to ignition source 7 - Sold in packs of 50 - Size: 76 x 51cm (30\"\" x 20\"\")",
  "DUSTPAN_BRUSH_SET_BLUE": "Professional Dustpan & Brush Set - Blue",
  "DUSTPAN_BRUSH_SET_GREEN": "Professional Dustpan & Brush Set - Green",
  "DUSTPAN_BRUSH_SET_RED": "Professional Dustpan & Brush Set - Red",
  "DUSTPAN_BRUSH_SET_YELLOW": "Professional Dustpan & Brush Set - Yellow",
  "EYEWEAR_SAFETY_GLASSES_CLEAR": "Safety Glasses",
  "EYEWEAR_SAFETY_GOGGLES_CLEAR": "Clear Safety Goggles",
  "FACEMASK_BLUE_50PACK": "Type IIR Disposable Medical Face Masks - 50Pack",
  "GLOVES_NITRILE-POLY_FOAM_L_10PACK": "Nitrile-Poly Foam Gloves - Large - Pack of 10",
  "GLOVES_NITRILE-POLY_FOAM_M_10PACK": "Nitrile-Poly Foam Gloves - Medium - Pack of 10",
  "GLOVES_NITRILE-POLY_FOAM_S_10PACK": "Nitrile-Poly Foam Gloves - Small - Pack of 10",
  "GLOVES_NITRILE-POLY_FOAM_XL_10PACK": "Nitrile-Poly Foam Gloves - XLarge - Pack of 10",
  "GLOVES_NITRILE_BLUE_L": "Large",
  "GLOVES_NITRILE_BLUE_MED": "Medium",
  "GLOVES_NITRILE_BLUE_SML": "Small",
  "GLOVES_NITRILE_BLUE_XL": "XLarge",
  "GLOVES_VINYL_CLEAR_L": "Large",
  "GLOVES_VINYL_CLEAR_MED": "Medium",
  "GLOVES_VINYL_CLEAR_SML": "Small",
  "GLOVES_VINYL_CLEAR_XL": "XLarge",
  "HI_VIS_BLUE_L": "Large",
  "HI_VIS_BLUE_M": "Medium",
  "HI_VIS_BLUE_S": "Small",
  "HI_VIS_BLUE_XL": "XLarge",
  "HI_VIS_BLUE_XXL": "XXLarge",
  "HI_VIS_ORANGE_L": "Large",
  "HI_VIS_ORANGE_LS_L": "Large",
  "HI_VIS_ORANGE_LS_M": "Medium",
  "HI_VIS_ORANGE_LS_S": "Small",
  "HI_VIS_ORANGE_LS_XL": "XLarge",
  "HI_VIS_ORANGE_LS_XXL": "XXLarge",
  "HI_VIS_ORANGE_M": "Medium",
  "HI_VIS_ORANGE_S": "Small",
  "HI_VIS_ORANGE_XL": "XLarge",
  "HI_VIS_ORANGE_XXL": "XXLarge",
  "HI_VIS_ORG/BLUE_EXEC_L": "Large",
  "HI_VIS_ORG/BLUE_EXEC_M": "Medium",
  "HI_VIS_ORG/BLUE_EXEC_S": "Small",
  "HI_VIS_ORG/BLUE_EXEC_XL": "XLarge",
  "HI_VIS_ORG/BLUE_EXEC_XXL": "XXLarge",
  "HI_VIS_PINK_L": "Large",
  "HI_VIS_PINK_M": "Medium",
  "HI_VIS_PINK_S": "Small",
  "HI_VIS_PINK_XL": "XLarge",
  "HI_VIS_PINK_XXL": "XXLarge",
  "HI_VIS_RED/GREY_EXEC_L": "Large",
  "HI_VIS_RED/GREY_EXEC_M": "Medium",
  "HI_VIS_RED/GREY_EXEC_S": "Small",
  "HI_VIS_RED/GREY_EXEC_XL": "XLarge",
  "HI_VIS_RED/GREY_EXEC_XXL": "XXLarge",
  "HI_VIS_RED_L": "Large",
  "HI_VIS_RED_M": "Medium",
  "HI_VIS_RED_S": "Small",
  "HI_VIS_RED_XL": "XLarge",
  "HI_VIS_RED_XXL": "XXLarge",
  "HI_VIS_YELL/R.NAVY_EXEC_L": "Large",
  "HI_VIS_YELL/R.NAVY_EXEC_M": "Medium",
  "HI_VIS_YELL/R.NAVY_EXEC_S": "Small",
  "HI_VIS_YELL/R.NAVY_EXEC_XL": "XLarge",
  "HI_VIS_YELL/R.NAVY_EXEC_XXL": "XXLarge",
  "HI_VIS_YELLOW_BS_L": "Large",
  "HI_VIS_YELLOW_BS_M": "Medium",
  "HI_VIS_YELLOW_BS_S": "Small",
  "HI_VIS_YELLOW_BS_XL": "XLarge",
  "HI_VIS_YELLOW_BS_XXL": "XXLarge",
  "HI_VIS_YELLOW_EXEC_L": "Large",
  "HI_VIS_YELLOW_EXEC_M": "Medium",
  "HI_VIS_YELLOW_EXEC_S": "Small",
  "HI_VIS_YELLOW_EXEC_XL": "XLarge",
  "HI_VIS_YELLOW_EXEC_XXL": "XXLarge",
  "HI_VIS_YELLOW_L": "Large",
  "HI_VIS_YELLOW_LS_L": "Large",
  "HI_VIS_YELLOW_LS_M": "Medium",
  "HI_VIS_YELLOW_LS_S": "Small",
  "HI_VIS_YELLOW_LS_XL": "XLarge",
  "HI_VIS_YELLOW_LS_XXL": "XXLarge",
  "HI_VIS_YELLOW_L_FA": "Large",
  "HI_VIS_YELLOW_M": "Medium",
  "HI_VIS_YELLOW_M_FA": "Medium",
  "HI_VIS_YELLOW_S": "Small",
  "HI_VIS_YELLOW_S_FA": "Small",
  "HI_VIS_YELLOW_XL": "XLarge",
  "HI_VIS_YELLOW_XL_FA": "XLarge",
  "HI_VIS_YELLOW_XXL": "XXLarge",
  "HI_VIS_YELLOW_XXL_FA": "XXLarge",
  "HNDL_SQUEEGEE_PLASTIC": "Plastic Handle",
  "HNDL_WOODEN": "Wooden Handle - (Per handle)",
  "HNDL_WOODEN_1": "Wooden Handle - (Per handle)",
  "HNDL_WOODEN_2": "Wooden Handle - (Per handle)",
  "IMPACT_LIQUIDS_MULTI_PURPOSE_5L": "5L Bottle - 1:120 Dilution Rate",
  "JUG_FUNNEL_6\"": "6\" Funnel",
  "JUG_MEASURING_1LITRE": "1L Measuring Jug",
  "LITTER_PICKER_34INCH": "Black Long Handled Litter Pick Up Tool",
  "LOBBY_BRUSH_LONGHNDL_COMPLETE_SET_BLACK": "Black",
  "LOBBY_BRUSH_LONGHNDL_COMPLETE_SET_BLUE": "Blue",
  "LOBBY_BRUSH_LONGHNDL_COMPLETE_SET_GREEN": "Green",
  "LOBBY_BRUSH_LONGHNDL_COMPLETE_SET_RED": "Red",
  "LOBBY_BRUSH_LONGHNDL_COMPLETE_SET_YELLOW": "Yellow",
  "MAINTENCE REFILL PADS_X20": "Maintenance Spill Pads – Spill Kit Refills Highly absorbent pads for rapid response to drink spills and small leaks around the convention venue. Supplied in bundles to replenish maintenance spill kits and keep teams ready to respond.",
  "MASK_DISP_DUSTCLEAR_50PK": "TYPE IIR Disposable Medical Face Mask",
  "MOP_DISP_BLUE_10PK": "Large Big White 120g - Blue Socket",
  "MOP_DISP_GREEN_10PK": "Large Big White 120g - Green Socket",
  "MOP_DISP_RED_10PK": "Large Big White 120g - Red Socket",
  "MOP_STAND_PY(12)_7OZ_BLUE": "Cotton String Mop Heads 150g - Blue Socket",
  "MOP_STAND_PY(12)_7OZ_GREEN": "Cotton String Mop Heads 150g - Green Socket",
  "MOP_STAND_PY(12)_7OZ_RED": "Cotton String Mop Heads 150g - Red Socket",
  "PUMP_30CC_FOR_5L": "30cc To fit 5L Chemical Bottle",
  "REFUSE_BIN_LINERS_CLEAR_1000PK": "Office Bin Liners X1000",
  "REFUSE_SACK_BLACK_100PK": "X100 Black Refuse Sacks",
  "REFUSE_SACK_CLEAR__100PK": "X100 Clear Refuse Sacks",
  "ROLLER_DIVIDE_100CMX200CM": "Roller Banner Screen Dividers These high-quality screens are lightweight, budget-friendly, and quick to set up or take down. The banner retracts neatly into the base for easy transport and compact storage. Dimension: 100cm (w) x 200cm (h).",
  "SCRAPER": "76mm (3\") Stiff Blade Scraper with Softgrip Handle",
  "SHARPS_CONTAINER_13L": "13L Sharps Container - Internal Capacity: 10.4L Overall Bin Dimension: (h)195 x (l)195 x (w)292mm",
  "SHARPS_CONTAINER_1L": "1L Sharps Container - Internal Capacity: 0.85L Overall Bin Dimension: (h)187 x (l)90 x (w)108mm",
  "SHARPS_CONTAINER_2L": "2L Sharps Container - Internal Capacity: 1.7L Overall Bin Dimension: (h)177 x (l)197 x (w)126mm",
  "SHARPS_CONTAINER_7L": "7L Sharps Container - Internal Capacity: 5.8L Overall Bin Dimension: (h)380 x (l)175 x (w)175mm",
  "SPILL_KITS_MAINTENANCE_10L": "10L Rapid Response Spill Kit - Clip Closed Bag Vinyl Bag Portable carry kit for quickly dealing with drink spills during conventions. Absorbent pads soak up tea, coffee and other liquids far faster than blue roll, while spill socks help contain moving spills and prevent spreading. Kit includes: - 10 x Maintenance Absorbent Pads - 1 x 1.2m Maintenance Absorbent Socks - 1 x Haz Waste Bags - 1 x Clip Top Bag - 1 x Tie",
  "SPILL_KITS_MAINTENANCE_15L": "15L Rapid Response Spill Kit - Clip Closed Bag Vinyl Bag Portable carry kit for quickly dealing with drink spills during conventions. Absorbent pads soak up tea, coffee and other liquids far faster than blue roll, while spill socks help contain moving spills and prevent spreading. Kit includes: - 15 x Maintenance Absorbent Pads - 1 x 1.2m Maintenance Absorbent Socks - 1 x Haz Waste Bags - 1 x Clip Top Bag - 1 x Tie",
  "SPILL_KITS_MAINTENANCE_20L": "20L Maintenance Spill Kits - Clip Closed Bag Vinyl Bag Portable carry kit for quickly dealing with drink spills during conventions. Absorbent pads soak up tea, coffee and other liquids far faster than blue roll, while spill socks help contain moving spills and prevent spreading. Kit includes: - 20 x Maintenance Absorbent Pads - 2 x 1.2m Maintenance Absorbent Socks - 1 x Haz Waste Bags - 1 x Clip Top Bag - 1 x Tie",
  "SPILL_KITS_MAINTENANCE_50L": "50L Maintenance Spill Kits - Clip Closed Bag Vinyl Bag Portable carry kit for quickly dealing with drink spills during conventions. Absorbent pads soak up tea, coffee and other liquids far faster than blue roll, while spill socks help contain moving spills and prevent spreading. Kit includes: - 50 x Pads - 4 x 1.2m Socks - 5 x Haz Waste Bags - 1 x Instruction Sheet - 5 x Tie - 1 x Holdall",
  "SQUEEGEE_METAL_55CM": "55cm Metal Floor Squeegee",
  "SQUEEGEE_PLASTIC_55CM": "55 cm Plastic Floor Squeegee",
  "TISSUE_FACIAL_100SHEETS": "Tiboo Luxury Unbleached Facial Tissues - 2ply - 100 Sheets - 100% Pure Bamboo - The sustainable choice - One of the fastest growing plants – no risk of a shortage - 2 ply luxury tissues that are strong and absorbent - Naturally hypoallergenic and contains no nasty chemicals - Extremely soft – not only is it eco-friendly, you also don’t have to compromise on softness! - Easy to dispense box - Sheets measuring 200mm x 180mm - Packed 100 tissues per pack",
  "TOILET_BRUSH_HOLDER_WHITE": "Brush & Holder - (h)395mm x (w)130mm x (d)130mm - White",
  "TRAVEL_BED": "Extra Wide Heavy Duty Portable Bed - Perfect for tall adults, heavy people, or family kids, teens, toddlers, children. - The folding cot for adults measures 75\"\"x28\"\"x15\"\" when open, 1 inch wider than usual. Pack size 41\"\"x9\"\"x7\"\". Weighes 17 pounds. The cot leg tubes measures 1.1\"\"x1.5\"\". The thicker sleeping cot bed ensures single person freedom movement in using. - No assembly required. The sleeping cot for adults can be easily installed or folded up into an included storage bag within 10 seconds. Convenient for rest or transport.",
  "TRG_COMPLETE_BLUE": "Solvent Resistant Trigger Spray Head & Bottle - Blue",
  "TRG_COMPLETE_GREEN": "Solvent Resistant Trigger Spray Head & Bottle - Green",
  "TRG_COMPLETE_RED": "Solvent Resistant Trigger Spray Head & Bottle - Red",
  "TRG_HEAD_ONLY_BLUE": "Solvent Resistant Trigger Spray Head - Blue",
  "TRG_HEAD_ONLY_GREEN": "Solvent Resistant Trigger Spray Head - Green",
  "TRG_HEAD_ONLY_RED": "Solvent Resistant Trigger Spray Head - Red",
  "TR_JUMBO_MINI_12PK": "12 Pack Mini Jumbo Toilet Rolls",
  "TR_STANDARD_WHITE_36PK": "36 Pack Standard Toilet Rolls",
  "VOMIT_BAGS_50PACK": "Emesis Vomit Bags 1000ml (50 Pack) - 1000ml capacity for safe collection of vomit or bodily fluids - Leak-resistant design for added hygiene - Clearly marked graduations every 100ml for accurate measurement - Easy to seal after use - Cleaner and more convenient than traditional basins, enabling faster cleanup",
  "WET_FLOOR_AFRAME": "A Frame 'Caution Wet Floor' Sign",
  "WHEEL_CHAIR_MKII": "High quality, entry level standard wheelchair. Suitable for everyday mobility. - Folds in seconds for transport or storage - Made of robust steel - Flip up foot rests for ease of access - Parking brakes - Total weight 18 KG - Front 8\"\" and rear 24\"\" full size wheels - Length - 108.5cm - Width - 61cm - Height - 91.5cm - Folded Width - 26.5cm - Folded Height - 75cm - Seat Width - 46cm (18\"\") - Seat Height to Ground - 50.5cm - Seat Depth - 41cm - Weight Capacity: 115kg (18 Stone)",
  "WRAP_CELLOPHANE_CLEAR": "Wrap Cellophone Clear",
};
