/**
 * pickList.ts
 * Client-side stock pick list generator — opens a print-optimised HTML page
 * in a new tab so warehouse staff can print it and physically check off items.
 * No external dependencies.
 */

export type PickListLine = {
  code: string;
  name: string;
  variant: string | null;
  category: string;
  qty: number;
};

const CATEGORY_LABELS: Record<string, string> = {
  safety_ppe: "Safety & PPE",
  janitorial: "Janitorial",
  chemicals: "Cleaning Chemicals",
  special: "Special Order",
  firstaid: "First Aid",
};

export function downloadPickList({
  conventionName,
  dept,
  items,
}: {
  conventionName: string;
  dept: "CS" | "FA";
  items: PickListLine[];
}) {
  const orderedItems = items.filter((i) => i.qty > 0);
  if (orderedItems.length === 0) {
    alert("No ordered items to print.");
    return;
  }

  const now = new Date();
  const dateStr = now.toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
  const deptLabel = dept === "CS" ? "Cleaning Supplies" : "First Aid";

  const grouped = orderedItems.reduce<Record<string, PickListLine[]>>((acc, i) => {
    if (!acc[i.category]) acc[i.category] = [];
    acc[i.category].push(i);
    return acc;
  }, {});

  const totalLines = orderedItems.length;
  const totalUnits = orderedItems.reduce((s, i) => s + i.qty, 0);

  const rows = Object.entries(grouped)
    .map(
      ([category, lines]) => `
    <tr class="cat-row"><td colspan="5">${CATEGORY_LABELS[category] ?? category}</td></tr>
    ${lines
      .map(
        (l) => `
    <tr>
      <td class="checkbox"><span class="box"></span></td>
      <td class="mono">${l.code}</td>
      <td>${l.name}</td>
      <td class="center">${l.variant ?? "—"}</td>
      <td class="right bold">${l.qty}</td>
    </tr>`
      )
      .join("\n")}`
    )
    .join("\n");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Pick List — ${conventionName} (${deptLabel})</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Arial, Helvetica, sans-serif; font-size: 10pt; color: #1e293b; background: white; }
    .page { padding: 18mm 18mm 16mm; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 18px; }
    .header-left h1 { font-size: 22pt; font-weight: 900; color: #0f172a; letter-spacing: -0.5px; }
    .header-left .org { color: #64748b; margin-top: 5px; font-size: 9pt; }
    .header-right { text-align: right; font-size: 9pt; color: #475569; }
    .header-right strong { color: #1e293b; }
    hr { border: none; border-top: 2px solid #e2e8f0; margin: 14px 0; }
    .stats { margin-bottom: 14px; font-size: 9pt; color: #64748b; }
    table { width: 100%; border-collapse: collapse; font-size: 9pt; }
    thead tr { background: #1e293b; color: #94a3b8; }
    thead th { padding: 8px 10px; text-align: left; font-weight: 600; font-size: 7.5pt; text-transform: uppercase; letter-spacing: 0.06em; }
    tbody td { padding: 7px 10px; border-bottom: 1px solid #e2e8f0; vertical-align: middle; }
    .cat-row td { background: #f1f5f9; font-weight: 700; font-size: 8pt; text-transform: uppercase; letter-spacing: 0.05em; color: #475569; padding: 6px 10px; }
    .checkbox { width: 24px; }
    .box { display: inline-block; width: 12px; height: 12px; border: 1.5px solid #64748b; }
    .mono { font-family: 'Courier New', monospace; color: #64748b; font-size: 8.5pt; }
    .center { text-align: center; }
    .right { text-align: right; }
    .bold { font-weight: 700; color: #0f172a; }
    .footer { margin-top: 14px; font-size: 8pt; color: #94a3b8; display: flex; justify-content: space-between; }
    @media print {
      @page { margin: 0; size: A4 portrait; }
      .page { padding: 12mm 14mm 12mm; }
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    }
  </style>
</head>
<body>
  <div class="page">
    <div class="header">
      <div class="header-left">
        <h1>Pick List</h1>
        <div class="org">${deptLabel} &middot; IBSA Convention Supplies</div>
      </div>
      <div class="header-right">
        <p><strong>${conventionName}</strong></p>
        <p>Date: ${dateStr}</p>
      </div>
    </div>

    <hr />

    <div class="stats">${totalLines} line${totalLines !== 1 ? "s" : ""} &middot; ${totalUnits} unit${totalUnits !== 1 ? "s" : ""} to pick</div>

    <table>
      <thead>
        <tr>
          <th></th>
          <th>Code</th>
          <th>Product</th>
          <th style="text-align:center">Variant</th>
          <th style="text-align:right">Qty</th>
        </tr>
      </thead>
      <tbody>
        ${rows}
      </tbody>
    </table>

    <div class="footer">
      <span>Generated by IBSA Portal &middot; ${dateStr}</span>
    </div>
  </div>

  <script>window.addEventListener('load', function() { window.print(); });</script>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) {
    alert("Popup blocked — please allow popups for this site and try again.");
    return;
  }
  win.document.write(html);
  win.document.close();
}
