-- NOTE: git field is Goods In Transit, actively used by POS — do NOT drop.
-- This file intentionally left as a no-op to avoid accidental re-execution.
-- The column was briefly removed and must be re-added if missing:
-- ALTER TABLE "IbsaProduct" ADD COLUMN IF NOT EXISTS "git" INTEGER NOT NULL DEFAULT 0;
